import tx1 from './01.expected'
import tx2 from './02.expected'
import tx3 from './remasc.expected'
import tx4 from './bridge_01.expected'
import tx5 from './bridge_02.expected'
import tx6 from './bridge_03.expected'
import tx7 from './bridge_04.expected'
import tx8 from './bridge_05.expected'
import tx9 from './09.expected'
export default [tx1, tx2, tx3, tx4, tx5, tx6, tx7, tx8, tx9]
